version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - mosquitto

  mqtt-host:
    build:
      context: ./host
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - mosquitto